baseurl = "/"
relativeURLs = true
uglyurls = true
title = "pico-go documentation"
languageCode = "en-us"
theme = "hugo-theme-docdock"
DefaultContentLanguage = "en"

[params]
themeStyle = "picogo"

[blackfriday]
  hrefTargetBlank = true # open the external links in a new window
  fractions = false

[outputs]
home = [ "HTML", "RSS", "JSON"]